/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.cameraview

import android.app.Activity
import android.util.Log
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.kroll.annotations.Kroll.proxy
import org.appcelerator.titanium.TiApplication
import org.appcelerator.titanium.proxy.TiViewProxy
import org.appcelerator.titanium.view.TiUIView
import ti.cameraview.camera.CameraUtils
import ti.cameraview.camera.CameraView
import ti.cameraview.constant.Defaults
import ti.cameraview.constant.Properties.ASPECT_RATIO
import ti.cameraview.constant.Properties.AUTO_FOCUS_RESUME_TIME
import ti.cameraview.constant.Properties.CAMERA_ID
import ti.cameraview.constant.Properties.FLASH_MODE
import ti.cameraview.constant.Properties.FOCUS_MODE
import ti.cameraview.constant.Properties.RESUME_AUTO_FOCUS
import ti.cameraview.constant.Properties.SCALE_TYPE
import ti.cameraview.constant.Properties.TORCH_MODE
import ti.cameraview.helper.PermissionHandler


@proxy(creatableInModule = TicameraviewModule::class, propertyAccessors = [
    CAMERA_ID,
    TORCH_MODE,
    FLASH_MODE,
    ASPECT_RATIO,
    SCALE_TYPE,
    FOCUS_MODE,
    RESUME_AUTO_FOCUS,
    AUTO_FOCUS_RESUME_TIME
])
class CameraViewProxy : TiViewProxy() {
    companion object {
        const val LCAT = "CameraViewProxy"
    }

    init {
        defaultValues[CAMERA_ID] = CameraUtils.getDefaultCameraId()
        defaultValues[TORCH_MODE] = Defaults.TORCH_MODE_OFF
        defaultValues[FLASH_MODE] = Defaults.FLASH_MODE_AUTO
        defaultValues[ASPECT_RATIO] = Defaults.ASPECT_RATIO_4_3
        defaultValues[SCALE_TYPE] = Defaults.SCALE_TYPE_FIT_CENTER
        defaultValues[FOCUS_MODE] = Defaults.FOCUS_MODE_AUTO
        defaultValues[RESUME_AUTO_FOCUS] = Defaults.RESUME_AUTO_FOCUS_AFTER_FOCUS_MODE_TAP
        defaultValues[AUTO_FOCUS_RESUME_TIME] = Defaults.RESUME_AUTO_FOCUS_TIME_AFTER_FOCUS_MODE_TAP
    }

    override fun createView(activity: Activity): TiUIView {
        val view: TiUIView = CameraView(this)
        view.layoutParams.autoFillsHeight = true
        view.layoutParams.autoFillsWidth = true
        return view
    }

    @Kroll.method
    public fun createCameraView() {
        if (CameraUtils.isCameraSupported() && PermissionHandler.hasCameraPermission() && PermissionHandler.hasStoragePermission()) {
            // create camera view if not ready yet
            (view as CameraView).apply {
                if (!this.isCameraReady()) {
                    this.createCameraPreview()
                }
            }
        } else {
            Log.d(CameraView.LCAT, "Camera permissions missing. Use Ti.Media.requestCameraPermissions to request required permissions")
        }
    }

    override fun onResume(activity: Activity?) {
        // handle the torch state since the torch is turned off whenever the activity goes in pause state
        (view as CameraView)?.handleTorch()
        Log.d(LCAT, "** onResume")
    }
}
