/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.cameraview

import android.app.Activity
import android.os.Bundle
import android.util.Log
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.kroll.annotations.Kroll.proxy
import org.appcelerator.titanium.proxy.TiViewProxy
import org.appcelerator.titanium.view.TiUIView
import ti.cameraview.camera.CameraFeatures
import ti.cameraview.camera.CameraView
import ti.cameraview.helper.PermissionHandler


@proxy(creatableInModule = TicameraviewModule::class, propertyAccessors = ["color"])
class CameraViewProxy : TiViewProxy() {
    companion object {
        const val LCAT = "CameraViewProxy"
    }

    override fun createView(activity: Activity): TiUIView {
        val view: TiUIView = CameraView(this)
        view.layoutParams.autoFillsHeight = true
        view.layoutParams.autoFillsWidth = true
        return view
    }

    @Kroll.method
    public fun createCameraView() {
        if (!CameraFeatures.isCameraSupported() ||
                !PermissionHandler.hasCameraPermission() ||
                !PermissionHandler.hasStoragePermission()) {
            Log.d(CameraView.LCAT, "Camera permissions missing. Use Ti.Media.requestCameraPermissions to request required permissions")
            return
        }

        (view as CameraView).createCameraPreview()
    }
}