/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.cameraview

import org.appcelerator.kroll.KrollModule
import org.appcelerator.kroll.annotations.Kroll
import org.appcelerator.titanium.TiApplication

@Kroll.module(name="ticameraview", id="ti.cameraview")
class TicameraviewModule : KrollModule() {
    companion object {
		@JvmStatic
		@Kroll.onAppCreate
		fun onAppCreate(app: TiApplication) {
			// put module init code that needs to run when the application is created
		}
	}
}